name: test

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, beta]
  schedule:
    # run daily at 00:00
    - cron: 0 0 * * *

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm playwright install --with-deps chromium
      - run: pnpm test
